
drop table usuari;

drop table membre_equip;

drop table equip;
drop table categoria;
drop table jugador;
drop table temporada;


CREATE TABLE usuari(
    login VARCHAR(30) NOT NULL,
    nom VARCHAR(50) NOT NULL,
    password VARCHAR(40) NOT NULL,
    CONSTRAINT PK_usuari PRIMARY KEY(login)
);

CREATE TABLE temporada(
    any_t NUMBER(4,0) NOT NULL,

    CONSTRAINT PK_temporada PRIMARY KEY(any_t)
);

CREATE TABLE jugador(
    id number(3,0) generated by default on null as identity,
    nom VARCHAR(30) NOT NULL,
    cognom VARCHAR(50) NOT NULL,
    sexe VARCHAR(1) NOT NULL,
    data_naix date NOT NULL,
    id_legal VARCHAR(10) NOT NULL,
    iban VARCHAR(10) NOT NULL,
    any_fi_reviso_medica date NOT NULL,
    adreca VARCHAR(50) NOT NULL,
    foto BLOB,
    
    CONSTRAINT jugador_CK_sexe CHECK (sexe IN ('H','D')),
    CONSTRAINT un_jugador_id_legal UNIQUE (id_legal),
    CONSTRAINT PK_jugador PRIMARY KEY(id)
);


CREATE TABLE categoria(
    id number(3,0) generated by default on null as identity,
    nom VARCHAR(30) NOT NULL,
    edat_min number(3,0) NOT NULL,
    edat_max number(3,0) NOT NULL,

    CONSTRAINT categoria_CK_edat CHECK (edat_min <= edat_max and edat_min > 0),
    CONSTRAINT un_categoria_name UNIQUE (nom),
    CONSTRAINT PK_categoria PRIMARY KEY(id)
);

CREATE TABLE equip(
    id number(3,0) generated by default on null as identity,
    nom VARCHAR(30) NOT NULL,
    tipus VARCHAR(1) NOT NULL,
    temporada NUMBER(4,0) NOT NULL,
    categoria number(3,0),
    
    CONSTRAINT fk_temporada_equip FOREIGN KEY(temporada) REFERENCES temporada(any_t),
    CONSTRAINT fk_categoria_equip FOREIGN KEY(categoria) REFERENCES categoria(id),
    CONSTRAINT equip_CK_tipus CHECK (tipus IN ('H','D','M')),
    CONSTRAINT PK_equip PRIMARY KEY(id) 
);

CREATE TABLE membre_equip(
    id_equip number(3,0)NOT NULL,
    id_jugador number(3,0)NOT NULL,
    titular_convidat VARCHAR(1) NOT NULL,
    
    CONSTRAINT fk_equip_membre_equip FOREIGN KEY(id_equip) REFERENCES equip(id),
    CONSTRAINT fk_jugador_membre_equip FOREIGN KEY(id_jugador) REFERENCES jugador(id),
    CONSTRAINT membre_equip_CK_titular_convidat CHECK (titular_convidat IN ('T','C')),
    CONSTRAINT PK_membre_equip PRIMARY KEY(id_equip,id_jugador)
);


CREATE OR REPLACE TRIGGER trg_hash_password_update
BEFORE INSERT OR UPDATE ON usuari
FOR EACH ROW
BEGIN
    IF :NEW.password IS NOT NULL AND :NEW.password != :OLD.password THEN
        :NEW.password := DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW(:NEW.password, 'AL32UTF8'), DBMS_CRYPTO.HASH_SH1);
    END IF;
END;
/



INSERT INTO usuari (login,nom,password) VALUES ('usuari','usuari','usuari');



INSERT INTO categoria (nom,edat_min,edat_max) VALUES ('Benjamí',7,8);
INSERT INTO categoria (nom,edat_min,edat_max) VALUES ('Aleví',9,10);
INSERT INTO categoria (nom,edat_min,edat_max) VALUES ('Infantil',11,13);
INSERT INTO categoria (nom,edat_min,edat_max) VALUES ('Cadet',14,15);
INSERT INTO categoria (nom,edat_min,edat_max) VALUES ('Juvenil',16,17);
INSERT INTO categoria (nom,edat_min,edat_max) VALUES ('Senior',18,21);
INSERT INTO categoria (nom,edat_min,edat_max) VALUES ('Vetera',22,125);


